### PR TITLE
Adding two new plop packs

### PR DESCRIPTION
**Pull request by bradgarropy**
[plop-pack-helpers](https://www.npmjs.com/package/@bradgarropy/plop-pack-helpers)
[plop-pack-actions](https://www.npmjs.com/package/@bradgarropy/plop-pack-actions)

### CODE REVIEW

**Comment by crutchcorn** [comment]
I love that you've made these! :D Do you think there's any way you can update your GH repo's descriptions to something that explains a bit more what they do and then re-run the generation command?

**Comment by bradgarropy** [comment]
Absolutely! I could actually use some advice in regards to how to package what I have.

`plop-pack-helpers` is a collection of three helpers: `date`, `slugify`, and `list`
`plop-pack-actions` is currently only one `copy` action, but I plan on adding more here later.

I was considering making each individual helper and action a separate package. Is that a better idea? Then describing them is easy. Otherwise, I'm kinda stuck describing them as "a useful collection of utility helpers".

Any thoughts?

**Comment by crutchcorn** [comment]
This is obviously a largwr technical debate, so take my opinion with a grain of salt. I'm personally, with Plop loads, in favor of individual packages. However, if you wanted to stick with the group, the description you outlined is a-okay

**Comment by bradgarropy** [comment]
Let's stay with these for now. And later I can split them out into separate packages and make another pull request.
I'll update the description and the PR!

**Comment by bradgarropy** [comment]
Updated the descriptions! I'll do some playing around with new package names here in a bit and possibly submit another PR.
Thanks!

**Comment by crutchcorn** [comment]
Sounds like a plan! No worries if you don't end up publishing new packages, either :) Thanks for the contribution!

**Comment by amwmedia** [comment]
Yeah, I'd suggest that we either make the description reference something about these being used for building your website, or break them into individual package so they can each have their own description. With the current structure, I fear we'll end up with a list of 10 `Plop Pack Actions` that all have the same description. 😉

**Comment by amwmedia** [comment]
Maybe even something like...

- [Plop Pack Actions](https://github.com/bradgarropy/plop-pack-actions) (BG Codes) - Collection of plop utility actions developed by [@bradgarropy](https://github.com/bradgarropy).
  - `copy` - short description of what copy does

@crutchcorn @bradgarropy thoughts?

**Pull request merged**
