### PR TITLE
Added IDE section

### PR DESCRIPTION
**Pull request by SamKirkland**

### CODE REVIEW

**Comment by crutchcorn** [comment]
Hey hey @SamKirkland ! Love the new section and your project! 

However, instead of editing the README directly, let's update the data.json file and have the changes generated. You can find info on how to do that in our CONTRIBUTING.md file :) 

Once that's changed, I'll merge ASAP

**Comment by SamKirkland** [comment]
Ooops got a bit too excited and didn't even look for a contributing file. Fixing now :)

**Comment by crutchcorn** [comment]
Awesome, thank you! :D

**Comment by SamKirkland** [comment]
**Thank you!**
Plop rocks! Probably saved us a few hundred thousand last year in dev effort.

**Pull request merged**
